-- MySQL Script generated by MySQL Workbench
-- Sat May 22 12:59:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema M15_Joc_Daus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema M15_Joc_Daus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `M15_Joc_Daus` ;
CREATE SCHEMA IF NOT EXISTS `M15_Joc_Daus` DEFAULT CHARACTER SET utf8 ;
USE `M15_Joc_Daus` ;



-- -----------------------------------------------------
-- Table `M15_Joc_Daus`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `M15_Joc_Daus`.`game` ;

CREATE TABLE IF NOT EXISTS `M15_Joc_Daus`.`game` (
  `game_id` INT(11) NOT NULL AUTO_INCREMENT,
  `dice1_value` INT(11) NOT NULL,
  `dice2_value` INT(11) NOT NULL,
  `game_won` TINYINT(4) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `M15_Joc_Daus`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO game (dice1_value, dice2_value, game_won, user_id) VALUES
(1,2,FALSE,1),
(3,3,FALSE,1),
(3,4,TRUE,2),
(1,2,FALSE,3),
(5,2,TRUE,4),
(6,2,FALSE,5),
(6,6,FALSE,6),
(1,6,TRUE,7);

-- -----------------------------------------------------
-- Table `M15_Joc_Daus`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `M15_Joc_Daus`.`user` ;

CREATE TABLE IF NOT EXISTS `M15_Joc_Daus`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `registration_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `meanScore` FLOAT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `nom_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


INSERT INTO user (name, meanScore) VALUES
('Angel', 0.0),
('Albert', 100.0),
('Llui', 0.0),
('Jefe', 100.0),
('Jefa', 0.0),
(NULL, 0.0),
(NULL, 100.0);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
